### ISSUE TITLE
FR text doesn't work

### ISSUE THREAD

**Issue by chinssa** [LauraWebdev/modern-habboexperience#1]
![image](https://github.com/LauraWebdev/modern-habboexperience/assets/26345852/9a60879e-f93d-428d-a2af-7e5a7964a618)
The text doesn't work in the french langage 
tested in edge and chrome

**Comment by LauraWebdev** [comment]
Seems to be invisible characters in the game data.

![image](https://github.com/LauraWebdev/modern-habboexperience/assets/7365286/62bc6917-e497-4a07-94e8-1ef35a0cb0bd)
![image](https://github.com/LauraWebdev/modern-habboexperience/assets/7365286/0e4d4882-8b05-40b4-b331-bff7617c5e1e)

**Comment by LauraWebdev** [comment]
This is now fixed on my hosted version
![image](https://github.com/LauraWebdev/modern-habboexperience/assets/7365286/d966ce03-98f7-4190-9c36-3aaaadf25d5a)
